### ISSUE TITLE
ModuleNotFound Error datatree 

### ISSUE THREAD

**Issue by semvijverberg** [nicrie/xeofs#112]
**Describe the bug**
When I add `xoefs` to my pyproject.toml, or when I install xeofs in a clean environment, it installs xeofs, but I gives the ModuleNotFoundError for the datatree dependency:

**Reproducible Minimal Working Example **

`conda create --name testxoefsdatatree python==3.10`
`conda activate testxoefsdatatree`
`pip install xeofs`
`python`

```
>>> import xeofs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/semv/miniconda3/envs/testxoefsdatatree/lib/python3.10/site-packages/xeofs/__init__.py", line 1, in <module>
    from xeofs import models, validation
  File "/Users/semv/miniconda3/envs/testxoefsdatatree/lib/python3.10/site-packages/xeofs/models/__init__.py", line 1, in <module>
    from .eof import EOF, ComplexEOF
  File "/Users/semv/miniconda3/envs/testxoefsdatatree/lib/python3.10/site-packages/xeofs/models/eof.py", line 6, in <module>
    from ._base_model import _BaseModel
  File "/Users/semv/miniconda3/envs/testxoefsdatatree/lib/python3.10/site-packages/xeofs/models/_base_model.py", line 18, in <module>
    from datatree import DataTree, open_datatree
ModuleNotFoundError: No module named 'datatree'
```

**Expected behavior**
No error ;).

**Additional context**
conda list output:
```
# packages in environment at /Users/semv/miniconda3/envs/testxoefsdatatree:
#
# Name                    Version                   Build  Channel
build                     1.0.3                    pypi_0    pypi
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cachecontrol              0.13.1                   pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
cftime                    1.6.3                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
cleo                      2.1.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
crashtest                 0.4.1                    pypi_0    pypi
dask                      2023.11.0                pypi_0    pypi
distlib                   0.3.7                    pypi_0    pypi
dulwich                   0.21.6                   pypi_0    pypi
fastjsonschema            2.18.1                   pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
installer                 0.7.0                    pypi_0    pypi
jaraco-classes            3.3.0                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
keyring                   24.2.0                   pypi_0    pypi
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.44.0               h091b4b1_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvmlite                  0.40.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
more-itertools            10.1.0                   pypi_0    pypi
msgpack                   1.0.7                    pypi_0    pypi
ncurses                   6.4                  h463b476_2    conda-forge
netcdf4                   1.6.5                    pypi_0    pypi
numba                     0.57.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.1.4                h0d3ecfb_0    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.3                    pypi_0    pypi
partd                     1.4.1                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6                    pypi_0    pypi
platformdirs              3.11.0                   pypi_0    pypi
poetry                    1.7.0                    pypi_0    pypi
poetry-core               1.8.1                    pypi_0    pypi
poetry-plugin-export      1.6.0                    pypi_0    pypi
pooch                     1.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyproject-hooks           1.0.0                    pypi_0    pypi
python                    3.10.0          h43b31ca_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
rapidfuzz                 3.5.2                    pypi_0    pypi
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.44.0               hf2abe2d_0    conda-forge
statsmodels               0.14.0                   pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.12.2                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
trove-classifiers         2023.11.9                pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
virtualenv                20.24.6                  pypi_0    pypi
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xarray                    2023.10.1                pypi_0    pypi
xattr                     0.10.1                   pypi_0    pypi
xeofs                     2.0.2                    pypi_0    pypi
xz                        5.2.6                h57fd34a_0    conda-forge
zipp                      3.17.0                   pypi_0    pypi
```

**Comment by semvijverberg** [comment]
Maybe a hint: when install v1.2.2, the installation is successful :). 

Thanks for any help in advance!

**Comment by nicrie** [comment]
Hey Sem, sorry about that and thanks for bringing up the issue!

I must admit that I'm puzzled as to why `pip` isn't installing `xarray-datatree`, even though it's listed as a dependency. Any thoughts, @slevang?

@semvijverberg, until we have a fix for this, you can try one of the following:

1. You can manually install the missing package using:

```bash
pip install xarray-datatree
```

2. Alternatively, you can install xeofs via conda/mamba, like so:

```bash
conda install -c conda-forge xeofs
```
or

```bash
mamba install xeofs
```

I've tested this, and conda correctly installs the dependencies in a fresh environment.

**Comment by nicrie** [comment]
Ah just realized that pip doesn't know anything about `tool.poetry.group` in `pyproject.toml`, so it's basically ignoring any groups apart from `tool.poetry.dependencies`. I'll fix that :)

**Comment by slevang** [comment]
Thanks for the fix @nicrie , I actually ran into this as well yesterday on pip install and was going to raise an issue. Figured it was something like that.

**Comment by semvijverberg** [comment]
Awesome! Thanks Niclas!
